### ISSUE TITLE
Setting "dock" type to window

### ISSUE THREAD

**Issue by drasill** [hash-bang/Conkie#1]
Hi,

I love Conkie so far, thank you !

I have to set the window type as `dock` (to have a i3wm toolbar).

It's easy as using `type: "dock"` when calling `win = new electron.BrowserWindow(...)`. But I want to be able to set this option from the theme.

Unlike the `setPosition` event, it seems like it's not possible to set the window type after the electron window is created.

Do you have any solution ?
I was thinking about a `<meta/>` tag in the HTML theme file, which would be parse in the `loadTheme` method; do you think it's ok ?

**Comment by hash-bang** [comment]
Its a tricky one really.

At the moment the theme files dictate pretty much everything about the apprentice like window position and so on.

Are you saying that position, style etc. should be moved to some user based option or just wanting to extend the existing theme API to cope with non-hardcoded window types?

**Comment by hash-bang** [comment]
The meta tag system you have in the PR works but it could also be possible to add a new event IPC call in similar to the existing `setPosition` but something like `setType`.

**Comment by drasill** [comment]
Yes, I did want to use a new event like setType.
But the window `type` has to be set when the window is created.

And the theme's javascript is executed afterward, so it's not possible to, say, send a `setType` event from the theme before the window creation.

That's why I used the meta tags.

**Comment by hash-bang** [comment]
Ah sorry. Slow on the uptake there.

Yeah you are right. There isn't really much that can be done with the late loading of the theme.

I've merged the PR in. I might move some of the other options into meta tags like this rather than setting them programatically.

Thanks for your help.

**Comment by drasill** [comment]
Thanks !
If you want me to move some options (which ones ?) into the meta tags, and update the documentation, I'd be happy to.

**Comment by hash-bang** [comment]
I guess the positioning stuff and the service registration are the two most obvious ones.

I'm just thinking - they should also be configurable by the user though if he wants to override the defaults.
