### ISSUE TITLE
Not working on Mint 17

### ISSUE THREAD

**Issue by ghost** [hash-bang/Conkie#3]
Have the following error on installing and running on Mint:

```
Uncaught Exception:
TypeError: Cannot read property 'split' of undefined
    at module.exports (/home/wescoder/.nvm/versions/node/v6.5.0/lib/node_modules/conkie/node_modules/require-grep/index.js:36:37)
    at Object.themeModule (/home/wescoder/.nvm/versions/node/v6.5.0/lib/node_modules/conkie/app.js:47:5)
    at /home/wescoder/.nvm/versions/node/v6.5.0/lib/node_modules/conkie/node_modules/async-chainable/index.js:552:32
    at /home/wescoder/.nvm/versions/node/v6.5.0/lib/node_modules/conkie/node_modules/async/lib/async.js:718:13
    at replenish (/home/wescoder/.nvm/versions/node/v6.5.0/lib/node_modules/conkie/node_modules/async/lib/async.js:319:21)
    at /home/wescoder/.nvm/versions/node/v6.5.0/lib/node_modules/conkie/node_modules/async/lib/async.js:330:15
    at _parallel (/home/wescoder/.nvm/versions/node/v6.5.0/lib/node_modules/conkie/node_modules/async/lib/async.js:717:9)
    at Object.async.parallelLimit (/home/wescoder/.nvm/versions/node/v6.5.0/lib/node_modules/conkie/node_modules/async/lib/async.js:735:9)
    at objectInstance._run (/home/wescoder/.nvm/versions/node/v6.5.0/lib/node_modules/conkie/node_modules/async-chainable/index.js:773:9)
    at objectInstance._execute (/home/wescoder/.nvm/versions/node/v6.5.0/lib/node_modules/conkie/node_modules/async-chainable/index.js:558:10)
```

**Comment by hash-bang** [comment]
After a bit of digging I'm going to guess that your `NODE_PATH` environment variable isn't set?

I've updated the sub-module responsible for plugin discovery so it doesn't cause everything to fall over.

Can you update (i.e. `npm install conkie@latest`) and let me know if you're still having an issue?

**Comment by ghost** [comment]
Well: `NODE_PATH=$(which node) nice conkie --background` runs Conkie but throws `[Conkie] ERR No theme file or matching module found`.

`NODE_PATH` maybe is not set because I'm using [nvm](https://github.com/creationix/nvm)? (I dunno)

**Comment by hash-bang** [comment]
Ok after a bit of fiddling I got it working. In the end I grabbed a boot CD to test it working on a completely blank setup.

An update to the NPM should fix everything on environments without NODE_PATH.

![Conkie on Mint - in all its glory](https://cloud.githubusercontent.com/assets/624527/18774401/0b47a44e-819c-11e6-924c-bc6b5846fd1a.png)

**Comment by ghost** [comment]
Trying with `conkie@latest` now and got the folowing:

```
$ conkie -vvv
[Conkie] Checking for binary wmctrl
[Conkie] Binary wmctrl found at /usr/bin/wmctrl
[Conkie] Setting up Electron instance
[Conkie] Electron app ready
[Conkie] ERR No theme file or matching module found
```

I suspect it is another issue, but I dunno how to proceed.

**Comment by hash-bang** [comment]
I assume you have `conkie-theme-default` installed?

Could you try updating it to the latest also, just so I can eliminate that as a possible fault?

**Comment by ghost** [comment]
Yeah, I already had it on latest.
I did uninstall, `npm cache clean`and install again, but still the same.

Could you try simulate on your machine with [nvm](https://github.com/creationix/nvm) too? I suspect it is something on that.

**Comment by hash-bang** [comment]
Sorry for the delay on this one. I'll have a look at nvm when I can and get back to you.

My guess is that NVM does something crazy with paths to support multiple installations of NPM modules which upsets the downstream [require-grep](https://github.com/hash-bang/require-grep#readme) component that locates other plugins. This component loads themes, stats and other bits that Conkie needs at runtime.

I'll keep you posted.
