### ISSUE TITLE
New theme

### ISSUE THREAD

**Issue by Heziode** [hash-bang/Conkie#4]
I create a simple Material theme :

![](https://raw.githubusercontent.com/Heziode-dev/conkie-theme-material/master/screenshot.png)

Can be download [in this repo](https://github.com/Heziode-dev/conkie-theme-material)

**Comment by Heziode** [comment]
Update theme, add box :

- CPU
- Memory
- Disks

**Comment by hash-bang** [comment]
Thanks!

I've added it to the main README.
