### ISSUE TITLE
node 4.x

### ISSUE THREAD

**Issue by twifty** [hash-bang/Conkie#6]
Is there any reason why this module requires node 6.x? It seems to run fine on version 4.

Node 4.x is a LTS release which doesn't expire for another year. IMO, it should be used as a minimum node version for all modules.

**Comment by hash-bang** [comment]
@twifty - short answer is that its my own residual paranoia. I'm coding in 6 myself and the giant sludge of node features can be a bit confusing between versions (e.g. does 4 cope with template literals? no idea without checking). So I find it easier to nail the version to what I'm currently using save in the knowledge that I can use the fancy new features without having to check each and every feature difference.

That being said, if you're using 4 and haven't noticed any issues or obvious errors I'm happy to put it down to 4. From memory though NPM just displays a warning and should install regardless of the engine being behind the recommendations.
